# Generated by Django 5.0.6 on 2024-05-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_alter_pais_options_alter_pais_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
    ]
