# Generated by Django 5.0.6 on 2024-05-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_provincia_alter_pais_options_remove_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
