# Generated by Django 5.0.6 on 2024-05-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='beneficio1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='beneficio2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='precio',
            field=models.IntegerField(default=100000),
        ),
    ]
